# Generated by Django 5.0.6 on 2024-05-19 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nav", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="father_id",
        ),
        migrations.AddField(
            model_name="category",
            name="father",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nav.category",
            ),
        ),
    ]
