# Generated by Django 5.0.6 on 2024-05-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nav", "0002_remove_category_father_id_category_father"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="weight",
            field=models.PositiveIntegerField(default=0, help_text="请输入正数，最大200"),
        ),
    ]
