# Generated by Django 5.0.6 on 2024-05-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nav", "0003_category_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="weight",
            field=models.PositiveIntegerField(default=0, help_text="请输入正数，最大100"),
        ),
    ]
