# Generated by Django 5.0.6 on 2024-05-19 07:47

import django.db.models.deletion
import nav.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nav", "0004_alter_category_weight"),
    ]

    operations = [
        migrations.CreateModel(
            name="Icon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="请输入图标标题", max_length=16, unique=True),
                ),
                (
                    "icon",
                    models.ImageField(
                        upload_to="static/media/",
                        validators=[nav.validators.validate_file_extension],
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="nav.icon"
            ),
        ),
    ]
