# Generated by Django 5.0.6 on 2024-05-19 08:51

import nav.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nav", "0005_icon_category_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="icon",
            name="path",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="icon",
            name="icon",
            field=models.ImageField(
                upload_to="icon/", validators=[nav.validators.validate_file_extension]
            ),
        ),
    ]
