# Generated by Django 5.0.6 on 2024-05-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nav", "0006_icon_path_alter_icon_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="icon",
            name="path",
        ),
        migrations.AlterField(
            model_name="icon",
            name="icon",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
