# Generated by Django 5.0.6 on 2024-05-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nav", "0007_remove_icon_path_alter_icon_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="icon",
            name="icon",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
