# Generated by Django 5.0.6 on 2024-05-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nav", "0009_alter_icon_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="icon",
            name="path",
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
