# Generated by Django 5.0.6 on 2024-05-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nav", "0010_icon_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="icon",
            name="path",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
