# Generated by Django 5.0.6 on 2024-05-19 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nav", "0011_alter_icon_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nav.icon",
            ),
        ),
        migrations.AlterField(
            model_name="icon",
            name="path",
            field=models.CharField(
                help_text="请输入图标地址", max_length=100, null=True, unique=True
            ),
        ),
    ]
