# Generated by Django 5.0.6 on 2024-05-19 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nav", "0012_alter_category_icon_alter_icon_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="AI_APP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="请输入站点名称", max_length=16, unique=True),
                ),
                ("description", models.CharField(help_text="简介", max_length=100)),
                (
                    "image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nav.icon",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="icon",
            name="nav",
            field=models.ManyToManyField(blank=True, null=True, to="nav.ai_app"),
        ),
    ]
