# Generated by Django 5.0.6 on 2024-05-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nav", "0013_ai_app_icon_app"),
    ]

    operations = [
        migrations.AlterField(
            model_name="icon",
            name="nav",
            field=models.ManyToManyField(blank=True, to="nav.ai_app"),
        ),
    ]
