# Generated by Django 5.0.6 on 2024-05-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nav", "0016_remove_icon_site_ai_app_site"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AI_APP",
            new_name="App",
        ),
        migrations.RemoveField(
            model_name="icon",
            name="nav",
        ),
        migrations.AddField(
            model_name="category",
            name="nav",
            field=models.ManyToManyField(to="nav.nav"),
        ),
    ]
